{'recording-count': 10408,
 'recording-list': [{'artist-credit': [{'artist': {'alias-list': [{'alias': 'Scott '
                                                                            'Anthony '
                                                                            'Arceneaux '
                                                                            'Jr.',
                                                                   'sort-name': 'Arceneaux, '
                                                                                'Scott '
                                                                                'Anthony '
                                                                                'Jr.',
                                                                   'type': 'Legal '
                                                                           'name'},
                                                                  {'alias': 'Scrim',
                                                                   'sort-name': 'Scrim'}],
                                                   'disambiguation': '$uicideboy$',
                                                   'id': 'c14c784b-2b14-492f-9eaf-269de7a87431',
                                                   'name': '$crim',
                                                   'sort-name': 'Scrim'},
                                        'name': '$crim'}],
                     'artist-credit-phrase': '$crim',
                     'ext:score': '100',
                     'id': '3fa2f162-3a12-4fb6-9c2f-203d8b44c719',
                     'isrc-list': ['QZAPK2000099'],
                     'length': '173514',
                     'release-list': [{'artist-credit': [{'artist': {'disambiguation': '$uicideboy$',
                                                                     'id': 'c14c784b-2b14-492f-9eaf-269de7a87431',
                                                                     'name': '$crim',
                                                                     'sort-name': 'Scrim'},
                                                          'name': '$crim'}],
                                       'artist-credit-phrase': '$crim',
                                       'country': 'XW',
                                       'date': '2020-05-15',
                                       'id': '993e1e3a-c7f5-4a0c-a207-8a09e98c55dd',
                                       'medium-count': 1,
                                       'medium-list': [{'format': 'Digital '
                                                                  'Media',
                                                        'position': '1',
                                                        'track-count': 20,
                                                        'track-list': [{'id': '036a1bee-13f9-49a3-8778-1e70b82419c1',
                                                                        'length': '173514',
                                                                        'number': '11',
                                                                        'title': 'Euphoria '
                                                                                 'Euphoria',
                                                                        'track_or_recording_length': '173514'}]}],
                                       'medium-track-count': 20,
                                       'release-event-list': [{'area': {'id': '525d4e18-3d00-31b9-a58b-a146a916de8f',
                                                                        'iso-3166-1-code-list': ['XW'],
                                                                        'name': '[Worldwide]',
                                                                        'sort-name': '[Worldwide]'},
                                                               'date': '2020-05-15'}],
                                       'release-group': {'id': '1b5e74d2-e65e-440c-9cbe-ad6e79f285e0',
                                                         'primary-type': 'Album',
                                                         'title': 'A Man Rose '
                                                                  'From The '
                                                                  'Dead',
                                                         'type': 'Album'},
                                       'status': 'Official',
                                       'title': 'A Man Rose from the Dead'},
                                      {'artist-credit': [{'artist': {'disambiguation': '$uicideboy$',
                                                                     'id': 'c14c784b-2b14-492f-9eaf-269de7a87431',
                                                                     'name': '$crim',
                                                                     'sort-name': 'Scrim'},
                                                          'name': 'Scrim'}],
                                       'artist-credit-phrase': 'Scrim',
                                       'country': 'XW',
                                       'date': '2020-05-15',
                                       'id': 'b002d295-8177-4e3d-a7d3-2e5b1ffd6b7f',
                                       'medium-count': 1,
                                       'medium-list': [{'format': 'Digital '
                                                                  'Media',
                                                        'position': '1',
                                                        'track-count': 20,
                                                        'track-list': [{'id': 'cb0e370e-b0a2-48c2-ae4a-de4d95427382',
                                                                        'length': '173000',
                                                                        'number': '11',
                                                                        'title': 'Euphoria '
                                                                                 'Euphoria',
                                                                        'track_or_recording_length': '173000'}]}],
                                       'medium-track-count': 20,
                                       'release-event-list': [{'area': {'id': '525d4e18-3d00-31b9-a58b-a146a916de8f',
                                                                        'iso-3166-1-code-list': ['XW'],
                                                                        'name': '[Worldwide]',
                                                                        'sort-name': '[Worldwide]'},
                                                               'date': '2020-05-15'}],
                                       'release-group': {'id': '1b5e74d2-e65e-440c-9cbe-ad6e79f285e0',
                                                         'primary-type': 'Album',
                                                         'title': 'A Man Rose '
                                                                  'From The '
                                                                  'Dead',
                                                         'type': 'Album'},
                                       'status': 'Official',
                                       'title': 'A Man Rose From The Dead'},
                                      {'artist-credit': [{'artist': {'disambiguation': '$uicideboy$',
                                                                     'id': 'c14c784b-2b14-492f-9eaf-269de7a87431',
                                                                     'name': '$crim',
                                                                     'sort-name': 'Scrim'},
                                                          'name': '$crim'}],
                                       'artist-credit-phrase': '$crim',
                                       'country': 'FR',
                                       'date': '2020-05-15',
                                       'id': '34a37a8e-0573-49c1-9626-76e32ca2ac72',
                                       'medium-count': 1,
                                       'medium-list': [{'format': 'Digital '
                                                                  'Media',
                                                        'position': '1',
                                                        'track-count': 20,
                                                        'track-list': [{'id': '3531bb7b-c27b-4402-ac8b-f0e848027466',
                                                                        'length': '173515',
                                                                        'number': '11',
                                                                        'title': 'Euphoria '
                                                                                 'Euphoria',
                                                                        'track_or_recording_length': '173515'}]}],
                                       'medium-track-count': 20,
                                       'release-event-list': [{'area': {'id': '08310658-51eb-3801-80de-5a0739207115',
                                                                        'iso-3166-1-code-list': ['FR'],
                                                                        'name': 'France',
                                                                        'sort-name': 'France'},
                                                               'date': '2020-05-15'}],
                                       'release-group': {'id': '1b5e74d2-e65e-440c-9cbe-ad6e79f285e0',
                                                         'primary-type': 'Album',
                                                         'title': 'A Man Rose '
                                                                  'From The '
                                                                  'Dead',
                                                         'type': 'Album'},
                                       'status': 'Official',
                                       'title': 'A Man Rose from the Dead'}],
                     'title': 'Euphoria Euphoria'}]}